// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRrbbTh1-koxYRXkYc-Ei0E1nCNsqyw7Y',
    appId: '1:177641639958:web:11c18cae11f46c8afe2537',
    messagingSenderId: '177641639958',
    projectId: 'fanintektechtest',
    authDomain: 'fanintektechtest.firebaseapp.com',
    storageBucket: 'fanintektechtest.firebasestorage.app',
    measurementId: 'G-4175Q28NZN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAU5A3dmspaZJ8dGXYJaWdepzM7EiFcGI4',
    appId: '1:177641639958:android:17ea71025b7bda77fe2537',
    messagingSenderId: '177641639958',
    projectId: 'fanintektechtest',
    storageBucket: 'fanintektechtest.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCm1hQnjDO-ku3HOK3ud3q-ztCXSB_FMSE',
    appId: '1:177641639958:ios:3a7e19bcfa6ff036fe2537',
    messagingSenderId: '177641639958',
    projectId: 'fanintektechtest',
    storageBucket: 'fanintektechtest.firebasestorage.app',
    iosBundleId: 'com.fanintek.agustinuszefanya.agustinuszefanyaMdtest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCm1hQnjDO-ku3HOK3ud3q-ztCXSB_FMSE',
    appId: '1:177641639958:ios:3a7e19bcfa6ff036fe2537',
    messagingSenderId: '177641639958',
    projectId: 'fanintektechtest',
    storageBucket: 'fanintektechtest.firebasestorage.app',
    iosBundleId: 'com.fanintek.agustinuszefanya.agustinuszefanyaMdtest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDRrbbTh1-koxYRXkYc-Ei0E1nCNsqyw7Y',
    appId: '1:177641639958:web:0513784115c3187efe2537',
    messagingSenderId: '177641639958',
    projectId: 'fanintektechtest',
    authDomain: 'fanintektechtest.firebaseapp.com',
    storageBucket: 'fanintektechtest.firebasestorage.app',
    measurementId: 'G-MHSKGPRPK7',
  );

}